---
- name: Play 1 - Install and configure Apache Web Server
  hosts: all
  #become: true
  #remote_user: root
  tasks:
    - name: Install Apache Web Server
      ansible.builtin.dnf:
        name: httpd

    - name: Enable and run Apache service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Copy index.html
      ansible.builtin.copy:
        src: web.html
        dest: /var/www/html/index.html
        mode: '644'

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled


- name: Play 2 - Check health of newly installed Apache Web Servers
  hosts: all
  connection: local
  gather_facts: no
  #vars:
  #  node: "node1"

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        #url: "http://{{ node }}"
        url: "http://{{ ansible_host }}"
