---
- name: Apache server installed
  hosts: web
  become: true
  remote_user: root
  tasks:

    # - name: Install Apache
    #   ansible.builtin.dnf:
    #     name: httpd

    # - name: Apache enabled and running
    #   ansible.builtin.service:
    #     name: httpd
    #     enabled: true
    #     state: started

    # - name: Copy index.html
    #   ansible.builtin.copy:
    #     src: web.html
    #     dest: /var/www/html/index.html
    #     mode: '644'


- name: Check URL
  hosts: all
  connection: local
  gather_facts: no
  #vars:
  #  node: "node1"

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        #url: "http://{{ node }}"
        url: "http://{{ ansible_host }}"
